name: Kodiak pipeline

on:
  - pull_request

jobs:
  run:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git log
      - run: sleep 5
