name: Kodiak pipeline

on:
  - pull_request
  - push

jobs:
  before:
    runs-on: ubuntu-20.04
    outputs:
      ALLOK: ${{ steps.git_refs.outputs.ALLOK }}
    steps:
      # - run: exit 1
      - run: echo "::set-output name=ALLOK::yes"

  run:
    runs-on: ubuntu-20.04
    needs:
      - before
    if: ${{always()}}
    env:
      ALLOK: ${{ needs.prepare.outputs.ALLOK}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: echo $ALLOK
      - run: git log
