name: Kodiak pipeline

on:
  - pull_request
  - push

jobs:
  before:
    runs-on: ubuntu-20.04
    outputs:
      ALLOK: ${{ steps.git_refs.outputs.ALLOK }}
    steps:
      # - run: exit 1
      - run: |
        echo "::set-output name=ALLOK::yes"
        echo "::set-env name=ALLOK::yes"
        echo $ALLOK

  run:
    runs-on: ubuntu-20.04
    needs:
      - before
    # if: ${{always()}}
    env:
      ALLOK: ${{ needs.before.outputs.ALLOK }}
    steps:
      - run: echo $ALLOK
