name: Kodiak pipeline

on:
  - pull_request
  - push

jobs:
  run:
    strategy:
      matrix:
        docker-type:
        projects:
        include:
          - docker-type: test
            projects: a,b
          - docker-type: test
            projects: c,d
          - docker-type: test2
            projects: 1,2
          - docker-type: test3
            projects: I
        # other:
        #   - oth1
        #   - oth2

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          echo 'something: ${{ matrix.something }}'
          echo 'other: ${{ matrix.other }}'
