name: Kodiak pipeline

on:
  - pull_request
  - push

jobs:
  run:
    strategy:
      matrix:
        something:
          - some1
          - some2
        other:
          - oth1
          - oth2

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
        echo 'something': ${{ matrix.something }}
        echo 'other': ${{ matrix.other }}
